[package]
name = "aoc2021-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.26.2"
counter = "0.5.2"
itermore = "0.1.0"
nalgebra = "0.29.0"
