[package]
name = "day02"
version = "0.1.0"
authors = ["Thomas Antony <tantony@purdue.edu>"]
edition = "2018"

[dependencies]

[[bin]]
name = "part01"
path = "src/part01.rs"

[[bin]]
name = "part02"
path = "src/part02.rs"